apiVersion: v1
kind: Pod
metadata:
  name: test-vddk-default-network
  namespace: vm-migration
  annotations:
    v1.multus-cni.io/default-network: vm-migration/vlan371-transfer-macvlan
spec:
  containers:
    - name: test
      image: registry.access.redhat.com/ubi9/ubi
      command:
        - sleep
        - '3600'
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
  restartPolicy: Always
