apiVersion: v1
kind: Pod
metadata:
  name: fedora-toolbox-default-network
  namespace: vm-migration
  annotations:
    v1.multus-cni.io/default-network: vm-migration/vlan371-transfer-macvlan
spec:
  containers:
    - name: fedora-toolbox
      image: quay.io/fedora/fedora-toolbox:latest
      command:
        - sleep
        - infinity
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "200m"
          memory: "256Mi"
  restartPolicy: Always
